<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>RegisterComplaint</title>

<link rel="stylesheet" href="CSS/registerComplaint.css">
</head>
<body>

	<div class="container">
		<p>Welcome to RegisterComplaint JSP</p>
		<form action="RegisterComplaint" method="post">
			<input class="inp" type="text" name="ticketNo" id="ticketNo" value="Ticket Number AutoGenerated" disabled/>
			<input class="inp" type="text" name="projectName" id="projectName" placeholder="Enter Project Name" required/>
			<input class="inp" type="text" name="moduleName" id="moduleName" placeholder="Enter Module Name" required/>
			<input class="inp" type="text" name="subModuleName" id="subModuleName" placeholder="Enter subModuleName" required/>
			
			<textarea class="inp" id="issue" name="issue" rows="8" cols="50" placeholder="Please enter your issue here" required></textarea>
			
			<div class="selectOption">
				
				<!-- <br><label>Issue Date</label>
			<input type="date" name="date" id="date" placeholder="Choose todays date" required/>
			 -->
			<br><br>
			<label>Priority</label>
			<select name="priority" id="priority">
				<option value="select" >select</option>
				  <option value="Critical">Critical</option>
				  <option value="High">High</option>
				  <option value="Medium">Medium</option>
			</select>
			<label>Status</label>
			<select name="status" id="status" autofocus>
				  <option value="select" >select</option>
				  <option value="New">New</option>
				  <option value="Assigned">Assigned</option>
				  <option value="Resolved">Resolved</option>
				  <option value="Closed">Closed</option>
			</select>
						
			<label>Frequency</label>
			<select name="frequency" id="frequency" autofocus>
				  <option value="" >select</option>
				  <option value="Always">Always</option>
				  <option value="Random">Random</option>
			</select>			
			</div>
			<br>
		<button>Register</button>
		</form>
		
	</div>
</body>
</html>